ALTER TABLE DETAILS.DETAIL ADD CONSTRAINT FK_Detail_Game FOREIGN KEY(ID) REFERENCES GAMES.GAME(ID);

ALTER TABLE REVIEWS.REVIEW ADD CONSTRAINT FK_Review_Game FOREIGN KEY(GAMEID) REFERENCES GAMES.GAME(ID);