CREATE SCHEMA IF NOT EXISTS REVIEWS;

CREATE TABLE REVIEWS.REVIEW ("ID" INTEGER not null primary key, "REVIEW" VARCHAR(500) not null, "REVIEWER" VARCHAR(100) not null, "RATING" INT not null, "GAMEID" INT not null);